const media = '/_next/static/media/';
const galleries = {
  elle: {title:'ELLE', intro:'ELLE has long been a partner for women in Hollywood — to connect, to provoke, to move the cultural needle.', images:[
    ['1_Elle_Panel-N_Lindsay_Lohan.4f7d1fd3.jpg','Lindsay Lohan','PHOTOGRAPH BY CHRIS COLLS'],['3_Elle_Panel-M_Rosalia_Cover.4511117b.jpg','Rosalía','PHOTOGRAPH BY INEZ & VINOODH'],['4_Elle_Panel-M_Zendaya_Cover.81b596ba.jpg','Zendaya','PHOTOGRAPH BY STEVEN KLEIN'],['6_Elle_Panel-A_Zoe_Saldana-min.0dfd8a47.jpg','Zoe Saldana','PHOTOGRAPH BY CASS BIRD'],['7_Elle_Panel-A_Julianne_Moore-min.95ab1dd8.jpg','Julianne Moore','PHOTOGRAPH BY COLLIER SCHORR'],['11_Elle_Panel-B_Lily-Rose_Depp-min.afbbb70a.jpg','Lily-Rose Depp','PHOTOGRAPH BY FELIX COOPER'],['14_Elle_Panel-C_Billie_Ellish-min.82ece76b.jpg','Billie Eilish','PHOTOGRAPH BY YVAN FABING'],['16_Elle_Panel-C_Margot_Robbie-min.f294a920.jpg','Margot Robbie','PHOTOGRAPH BY TERRY TSIOLIS'],['28_Elle_Panel-F_SZA.4224a5cc.jpg','SZA','PHOTOGRAPH BY RENELL MEDRANO'],['32_Elle_Panel-F_Danielle_Deadwyler.a125b997.jpg','Danielle Deadwyler','PHOTOGRAPH BY MICAIAH CARTER'],['37_Elle_Panel-G_Jennifer_Lopez.f2e59d1d.jpg','Jennifer Lopez','PHOTOGRAPH BY SØLVE SUNDSBØ'],['46_Elle_Panel-K_Jodie_Foster.b0f3c2f8.jpg','Jodie Foster','PHOTOGRAPH BY ZOEY GROSSMAN'] ]},
  esquire: {title:'ESQUIRE', intro:'Esquire has been documenting the men who shape culture, cinema and the world around them for generations.', images:[
    ['3_ESQ100122Cover_lo_Matt.789c7f87.jpg','Matt Smith','PHOTOGRAPH BY ESQUIRE ARCHIVES'],['12_North Gallery - Panel C_02_RB_Sean Connery.8f02efea.jpg','Sean Connery','PHOTOGRAPH BY ESQUIRE ARCHIVES'],['16_North Gallery - Panel C_05_RB_Tom Cruise.5533a760.jpg','Tom Cruise','PHOTOGRAPH BY ESQUIRE ARCHIVES'],['19_North Gallery - Panel D_01_Robert DeNiro.96b88233.jpg','Robert De Niro','PHOTOGRAPH BY ESQUIRE ARCHIVES'],['20_North Gallery - Panel D_02_Harrison Ford.0dee5c5b.jpg','Harrison Ford','PHOTOGRAPH BY ESQUIRE ARCHIVES'],['24_ESQ199503_Sharon_Stone__01_RB.09686042.jpg','Sharon Stone','PHOTOGRAPH BY ESQUIRE ARCHIVES'],['34_ESQ040123Cover_lo_pedro-min.a7dfa1bc.jpg','Pedro Pascal','PHOTOGRAPH BY ESQUIRE ARCHIVES'],['39_ESQ060122Cover_lo_Eliot-min.acc9e74d.jpg','Elliot Page','PHOTOGRAPH BY ESQUIRE ARCHIVES'] ]}
};
function route(){return location.pathname.replace(/^\//,'').replace(/\/$/,'')||'home'}
function shell(content){return `<div class="app-shell"><div class="grain"></div><header class="topbar"><a class="wordmark" href="/">ELLE × ESQUIRE</a><button class="menu-button" data-menu><span></span>Menu</button></header>${content}</div>`}
function home(){return shell(`<main class="hero"><h1><span>THE</span><em>ELLE</em><span>AND ESQUIRE</span><em>HOLLYWOOD</em></h1><p class="hero-sub">AS SEEN IN THE HEARST TOWER, LOCATED IN<br>NEW YORK CITY</p><span class="scroll-cue">SCROLL TO EXPLORE</span></main>${menu()}`)}
function intro(key){const g=galleries[key];return shell(`<main class="intro"><div class="intro-media"><img src="${media}${key==='elle'?'elle-intro-1.eab5514e.jpg':'esquire-intro-1.70e12053.jpg'}"><img src="${media}${key==='elle'?'elle-intro-2.a19697a3.jpg':'esquire-intro-2.248695fa.jpg'}"></div><div class="intro-copy"><div class="eyebrow">Hearst Galleries · 2026</div><h1>${g.title}<br>Hollywood</h1><p>${g.intro}</p><p>Explore a selection from the brands’ archival collections, presented as a cinematic walk through the many faces of a changing Hollywood.</p><a class="enter" href="/${key}">ENTER THE GALLERY ↗</a></div></main>${menu()}`)}
function gallery(key){const g=galleries[key];return shell(`<main class="gallery"><div class="gallery-head"><div><a class="back-link" href="/">← The New Hollywood</a><h1>${g.title}</h1></div><span class="gallery-count">${String(g.images.length).padStart(2,'0')} PORTRAITS</span></div><section class="gallery-grid">${g.images.map((x,i)=>`<button class="tile" data-index="${i}" data-gallery="${key}"><img loading="lazy" src="${media}${x[0]}" alt="${x[1]}"><span class="tile-meta"><span class="tile-name">${x[1]}</span><span class="tile-credit">${x[2]}</span></span></button>`).join('')}</section></main>${menu()}<div class="lightbox" data-lightbox><button class="lightbox-close" data-close>Close ×</button><button class="lightbox-prev" data-prev>← Prev</button><img data-lightbox-image alt=""><button class="lightbox-next" data-next>Next →</button></div>`)}
function menu(){return `<aside class="menu-panel" data-panel><button class="menu-close" data-menu>Close ×</button><nav><a href="/elle-intro">ELLE</a><a href="/esquire-intro">ESQUIRE</a><a href="/">THE EXHIBITION</a></nav></aside>`}
const current=route();document.querySelector('#app').innerHTML=current==='home'?home():current==='elle'?gallery('elle'):current==='esquire'?gallery('esquire'):current==='elle-intro'?intro('elle'):current==='esquire-intro'?intro('esquire'):home();
document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',()=>document.querySelector('[data-panel]').classList.toggle('is-open')));
const lb=document.querySelector('[data-lightbox]'); if(lb){let key=current,index=0;const img=lb.querySelector('[data-lightbox-image]');const show=()=>{const item=galleries[key].images[index];img.src=media+item[0];img.alt=item[1]};document.querySelectorAll('.tile').forEach(t=>t.addEventListener('click',()=>{index=Number(t.dataset.index);lb.classList.add('is-open');show()}));lb.querySelector('[data-close]').onclick=()=>lb.classList.remove('is-open');lb.querySelector('[data-prev]').onclick=()=>{index=(index-1+galleries[key].images.length)%galleries[key].images.length;show()};lb.querySelector('[data-next]').onclick=()=>{index=(index+1)%galleries[key].images.length;show()};document.addEventListener('keydown',e=>{if(e.key==='Escape')lb.classList.remove('is-open');if(e.key==='ArrowRight')lb.querySelector('[data-next]').click();if(e.key==='ArrowLeft')lb.querySelector('[data-prev]').click()})}
